"""Pass-2 multi-task model: elo-agnostic encoder + FOUR heads, all flat (not factored):
  human_head   1792-way move policy, elo-conditioned (single head, replaces the 12 per-band heads)
  sf_move_head 1792-way Stockfish best-move policy (objective; NOT elo-conditioned)
  value_head   WDL (3-way, elo-conditioned) — reused
  eval_head    scalar Stockfish eval, tanh(cp/400) (objective)

Flat move heads score a 64x64 (from,to) matrix bilinearly from the per-square encoder features, then
gather the 1792 geometrically-possible pairs (style_policy.move_index). The legal mask is the EXACT
per-position legal move set, generated by the dataloader (board reconstruction -> move_index
.legal_index_mask) — the stored from_legal/to_legal marginals CANNOT be used for a flat head because
to_legal is conditioned on the human from-square (it drops moves from other sources). Promotions are
ignored (queen)."""
from __future__ import annotations
import torch
import torch.nn as nn
from style_policy.board_encoder import BoardEncoder
from style_policy.value_head import WDLHead
from style_policy.packed_codec import packed_to_board_tensor
from style_policy import move_index

_NEG = -1e9                                                # finite mask sentinel (safe in CE/softmax grads)


class FlatMoveHead(nn.Module):
    """Bilinear (from,to) scorer over the 1792 flat move space, with optional elo FiLM conditioning."""
    def __init__(self, d_model: int, k: int = 64, cond_dim: int = 0):
        super().__init__()
        self.k = k
        self.norm = nn.LayerNorm(d_model)                       # stabilize logit magnitude vs encoder scale
        self.q = nn.Linear(d_model, k)
        self.key = nn.Linear(d_model, k)
        self.film = nn.Linear(d_model + cond_dim, 2 * d_model)   # FiLM squares from cls (+ elo cond)
        self.register_buffer("idx_ft", torch.tensor(move_index.IDX_FT, dtype=torch.long), persistent=False)

    def forward(self, cls: torch.Tensor, squares: torch.Tensor, cond: torch.Tensor | None = None) -> torch.Tensor:
        c = cls if cond is None else torch.cat([cls, cond], dim=-1)
        gamma, beta = self.film(c).chunk(2, dim=-1)             # (B,d) each
        sq = self.norm(squares * (1 + gamma.unsqueeze(1)) + beta.unsqueeze(1))   # (B,64,d)
        q = self.q(sq); key = self.key(sq)                     # (B,64,k)
        s = torch.einsum("bfk,btk->bft", q, key) / (self.k ** 0.5)   # (B,64,64)
        return s.reshape(s.shape[0], 64 * 64).index_select(1, self.idx_ft)   # (B,1792)


class FlatMultiTaskPolicy(nn.Module):
    def __init__(self, encoder, human_head, sf_move_head, value_head, eval_head, elo_emb, n_elo_buckets):
        super().__init__()
        self.encoder = encoder
        self.human_head = human_head
        self.sf_move_head = sf_move_head
        self.value_head = value_head
        self.eval_head = eval_head
        self.elo_emb = elo_emb                                 # (n_elo+1, elo_dim); null bucket = n_elo
        self.n_elo = n_elo_buckets

    @classmethod
    def from_config(cls, cfg: dict) -> "FlatMultiTaskPolicy":
        d = int(cfg["d_model"]); h = int(cfg["head_hidden"])
        enc = BoardEncoder(d_model=d, n_layers=int(cfg["n_layers"]), nhead=int(cfg["nhead"]),
                           dim_feedforward=int(cfg["dim_feedforward"]), dropout=float(cfg["dropout"]),
                           use_castling_ep=bool(cfg.get("use_castling_ep", False)),
                           use_last_move=bool(cfg.get("use_last_move", False)),
                           n_history_ply=int(cfg.get("n_history_ply", 0)),
                           use_gab=bool(cfg.get("use_gab", False)),
                           gab_d1=int(cfg.get("gab_d1", 8)), gab_d2=int(cfg.get("gab_d2", 64)))
        elo_dim = int(cfg.get("elo_dim", 32)); n_elo = int(cfg.get("n_elo_buckets", 40))
        elo_emb = nn.Embedding(n_elo + 1, elo_dim)             # +1 null bucket (unconditioned)
        human = FlatMoveHead(d, cond_dim=elo_dim)              # elo-conditioned human policy
        sfmove = FlatMoveHead(d, cond_dim=0)                   # objective best-move policy
        value = WDLHead(d_model=d, hidden=h, elo_dim=elo_dim, n_elo_buckets=n_elo)
        evalh = nn.Sequential(nn.Linear(d, h), nn.GELU(), nn.Linear(h, 1))
        return cls(enc, human, sfmove, value, evalh, elo_emb, n_elo)

    def encode(self, packed_pre, hist=None):
        board = packed_to_board_tensor(packed_pre).to(next(self.parameters()).device)
        return self.encoder(board, hist=hist)

    def human_logits(self, cls, squares, elo_idx) -> torch.Tensor:
        return self.human_head(cls, squares, cond=self.elo_emb(elo_idx))

    def sf_move_logits(self, cls, squares) -> torch.Tensor:
        return self.sf_move_head(cls, squares)

    def eval_value(self, cls) -> torch.Tensor:
        return torch.tanh(self.eval_head(cls).squeeze(-1))     # (B,) in [-1,1]


def masked_move_ce(logits: torch.Tensor, target_idx: torch.Tensor, legal_mask: torch.Tensor | None = None,
                   valid: torch.Tensor | None = None) -> torch.Tensor:
    """Cross-entropy over the 1792 moves. If legal_mask is given, restrict to legal moves (inference /
    masked train); if None, plain CE over all 1792 (unmasked train — the model learns legality; mask
    only at inference). `valid` (B,) bool masks out rows w/o a target (SF failures / unlabeled)."""
    masked = logits if legal_mask is None else logits.masked_fill(~legal_mask, _NEG)
    ce = nn.functional.cross_entropy(masked, target_idx, reduction="none")
    if valid is None:
        return ce.mean()
    v = valid.float()
    return (ce * v).sum() / v.sum().clamp(min=1.0)
